theme: minima
title: Alena Thomas
author: Alena Thomas
email: amthomas@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This a website project for AP Comp Sci A!

# social links
instagram_username: alena.mary.thomas
github_username: alenamarythomas
snapchat_username: alenamaryy
show_excerpts: true # set to false to remove excerpts on the homepage
